package: openshift-gitops-operator
supportedOCP: [v4.12, v4.13, v4.14, v4.15, v4.16, v4.17, v4.18, v4.19, v4.20]
channels:
  - name: gitops-1.15
    versions:
      - name: openshift-gitops-operator.v1.15.4
        replaces: openshift-gitops-operator.v1.15.3
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:0b1771f697a700263c5b827dbde56a5c9bab610e9d7df55ef93885a4e54cc0e9
  - name: gitops-1.16
    versions:
      - name: openshift-gitops-operator.v1.16.2
        replaces: openshift-gitops-operator.v1.16.1
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:cc14268ddbd89c654124439711249fc888a50de97ddf0e29d9665cd490bb1aeb
      - name: openshift-gitops-operator.v1.16.3
        replaces: openshift-gitops-operator.v1.16.2
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:8441322a0fce02df407573675b5b5d92d56de97c8aec72541b33d2dadc4050d5
      - name: openshift-gitops-operator.v1.16.4
        replaces: openshift-gitops-operator.v1.16.3
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:78dc89a4a9dfb8dcf93224fd9a3caa63ea1551f8da73a88aebb284123d4a2962
      - name: openshift-gitops-operator.v1.16.5
        replaces: openshift-gitops-operator.v1.16.4
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:1e7fb9262023798711dc58fecf9c57c2fbd260a7f942eef2a9fd2822dbfb0b74
  - name: gitops-1.17
    versions:
      - name: openshift-gitops-operator.v1.17.0
        replaces: openshift-gitops-operator.v1.16.2
        skipRange: ">=1.0.0 <1.17.0"
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:58cfcb4b920d75b83ed2662a8e226724075518ad105f42f2f497dc4463a3221f
      - name: openshift-gitops-operator.v1.17.1
        replaces: openshift-gitops-operator.v1.17.0
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:be93be0341649215fb001725aac0c3c5925343adbf1ad00c979b8c3d489512d6
      - name: openshift-gitops-operator.v1.17.2
        replaces: openshift-gitops-operator.v1.17.1
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:4fc82c51692138acd9a7232fc4b3451cbca9f7be763452c811bea7a68867cb93
      - name: openshift-gitops-operator.v1.17.3
        replaces: openshift-gitops-operator.v1.17.2
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:e1101b02df32a56a9aec80639372248b72963240dc86add446d0d07da65baca7
  - name: gitops-1.18
    versions:
      - name: openshift-gitops-operator.v1.18.0
        replaces: openshift-gitops-operator.v1.17.1
        skipRange: ">=1.0.0 <1.18.0"
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:8546401f9a96b0c397da8ab26306cca412e6fa6d11471c739177a5f533ba6f11
      - name: openshift-gitops-operator.v1.18.1
        replaces: openshift-gitops-operator.v1.18.0
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:a27b8dd047e10fbbd6fc49176036c9b5178a1d2841e26719bfde23239ede157d
      - name: openshift-gitops-operator.v1.18.2
        replaces: openshift-gitops-operator.v1.18.1
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:b4d6b30d562e1cacbb1ca461e8c14b95c0d42be1baf876599c446669f2584feb
      - name: openshift-gitops-operator.v1.18.3
        replaces: openshift-gitops-operator.v1.18.2
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:0372978e235a4a0a2169ce2c41ffd64ff57030025179cbb9d0d4f6136521d9dc
  - name: gitops-1.19
    versions:
      - name: openshift-gitops-operator.v1.19.0
        replaces: openshift-gitops-operator.v1.18.2
        skipRange: '>=1.0.0 <1.19.0'
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:5e78b9e6a98218c209af1d85e60c2000172a90f178f32f06f0e3b6bc11f33cce
