package: openshift-gitops-operator
supportedOCP: [v4.12, v4.13, v4.14, v4.15, v4.16, v4.17, v4.18, v4.19, v4.20, v4.21]
channels:
  - name: gitops-1.17
    versions:
      - name: openshift-gitops-operator.v1.17.0
        replaces: openshift-gitops-operator.v1.16.2
        skipRange: ">=1.0.0 <1.17.0"
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:58cfcb4b920d75b83ed2662a8e226724075518ad105f42f2f497dc4463a3221f
      - name: openshift-gitops-operator.v1.17.1
        replaces: openshift-gitops-operator.v1.17.0
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:be93be0341649215fb001725aac0c3c5925343adbf1ad00c979b8c3d489512d6
      - name: openshift-gitops-operator.v1.17.2
        replaces: openshift-gitops-operator.v1.17.1
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:4fc82c51692138acd9a7232fc4b3451cbca9f7be763452c811bea7a68867cb93
      - name: openshift-gitops-operator.v1.17.3
        replaces: openshift-gitops-operator.v1.17.2
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:e1101b02df32a56a9aec80639372248b72963240dc86add446d0d07da65baca7
      - name: openshift-gitops-operator.v1.17.4
        replaces: openshift-gitops-operator.v1.17.3
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:710f6fe3896177cae0d900643b7147d11410e5e58ee012e139fbeee308ee297b
  - name: gitops-1.18
    versions:
      - name: openshift-gitops-operator.v1.18.0
        replaces: openshift-gitops-operator.v1.17.1
        skipRange: ">=1.0.0 <1.18.0"
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:8546401f9a96b0c397da8ab26306cca412e6fa6d11471c739177a5f533ba6f11
      - name: openshift-gitops-operator.v1.18.1
        replaces: openshift-gitops-operator.v1.18.0
        skipRange: ""
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:a27b8dd047e10fbbd6fc49176036c9b5178a1d2841e26719bfde23239ede157d
      - name: openshift-gitops-operator.v1.18.2
        replaces: openshift-gitops-operator.v1.18.1
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:b4d6b30d562e1cacbb1ca461e8c14b95c0d42be1baf876599c446669f2584feb
      - name: openshift-gitops-operator.v1.18.3
        replaces: openshift-gitops-operator.v1.18.2
        skipRange: ''
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:a4e9887db8647c4e958df4725f08340a9c6a462cd18fd2bf9c9f1fc939649740
  - name: gitops-1.19
    versions:
      - name: openshift-gitops-operator.v1.19.0
        replaces: openshift-gitops-operator.v1.18.2
        skipRange: '>=1.0.0 <1.19.0'
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:5e78b9e6a98218c209af1d85e60c2000172a90f178f32f06f0e3b6bc11f33cce
      - name: openshift-gitops-operator.v1.19.1
        replaces: openshift-gitops-operator.v1.19.0
        skipRange: '>=1.0.0 <1.19.0'
        bundle: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle@sha256:b5429c67a872f0d75e927339451bff0a646f55f3cf0ab98f68c1da2cd610fbc7
